name: Auto version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to put in pom'
        required: false

env:
  # conditionals envs

  VERSION: ${{ github.event.inputs.version }}
  ACT_HAS_VERSION: ${{ github.event.inputs.version != '' }}
  NEW_BRANCH: release/${{ github.event.inputs.version }}
  # workflow envs
  APP_NAME: Auto version test

jobs:
  change_versions:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.4-eclipse-temurin-17

    steps:
      - name: Checkout APP repository
        uses: actions/checkout@v3
      - name: Execute vbum for version ${{env.VERSION}}
        shell: bash
        run: |
          mvn versions:set -DnewVersion=${{env.VERSION}}
          mvn versions:commit
          sed -i -E 's/(image: wefox\/.+:)(.+)/\1${{env.VERSION}}/g' docker-compose.yml
          rm docker-compose.yml-e;
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Auto commit for new version ${{ env.VERSION }}
          branch: ${{env.NEW_BRANCH}}
          commit-message: Auto pom changes for ${{ env.VERSION }}